- name: Installation packages and services for Web server
  yum:
    name: '{{ item }}'
    state: installed
  loop: '{{ packages }}'
  tags: installaton

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: true
  tags: started firewalld

- name: Insert firewalld rule for apache
  firewalld:
    port: '{{ httpd_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
  tags: open port for apache

- name: Insert firewalld rule for mysql
  firewalld:
    port: '{{ mysql_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
  tags: open port for mysql

- name: Set index.php as the default page
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DirectoryIndex index.html'
    replace: '#DirectoryIndex index.html \nDirectoryIndex index.php'
  tags: changed to php file

- name: Start Apache service
  service: 
    name: httpd
    enabled: true
    state: started
  tags: started apache

- name: Copy the code from repository
  git: 
    repo: '{{ repository }}' 
    dest: /var/www/html/ 
    force: yes
  tags: clone repo


